{% set name = "pyclarify" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyclarify-{{ version }}.tar.gz
  sha256: fdc7c3b2779763094bacaca12c6cc7fcdecf908cbd685fb26bc7cdf9fd52934c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=57
    - wheel
    - pip
  run:
    - python >=3.8
    - requests
    - pydantic >=2.0,<3.dev0

test:
  imports:
    - pyclarify
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/clarify/pyclarify
  summary: Python SDK for reading and writing signals to Clarify.
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.txt
  doc_url: https://clarify.github.io/pyclarify/
  dev_url: https://github.com/clarify/pyclarify

extra:
  recipe-maintainers:
    - oddaspa
